#!/bin/sh

# Copyright (c) 2020-present Sven Greb <development@svengreb.de>
# This source code is licensed under the MIT license found in the LICENSE file.

# The configuration for husky.
#
# References:
#   1. https://github.com/typicode/husky

. "$(dirname "$0")/_/husky.sh"

npm exec lint-staged
