# Copyright (c) 2020-present Sven Greb <development@svengreb.de>
# This source code is licensed under the MIT license found in the LICENSE file.

# GitHub Action Workflow for continuous integration jobs.
# See https://docs.github.com/en/actions and https://github.com/features/actions for more details.

name: ci
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
jobs:
  lint-node:
    runs-on: ubuntu-latest
    steps:
      - name: Print metadata and context information
        run: |
          echo "Git SHA: $GITHUB_SHA"
          echo "Git Ref: $GITHUB_REF"
          echo "Workflow Actor: $GITHUB_ACTOR"
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: "Setup Node.js version 14.x"
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "14.x"
      - name: Install Node modules
        run: yarn --frozen-lockfile
      - name: Run linters
        run: yarn lint
